# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcloud',
            name='school',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
