# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-19 08:20
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_wordcloud_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcloud',
            name='terms',
            field=jsonfield.fields.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
