# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_mining', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='flag',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
