# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_mining', '0003_auto_20161118_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='created_at',
            field=models.DateTimeField(default='2016-11-19 12:00:00+00:00'),
        ),
    ]
