# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_mining', '0005_auto_20161119_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='idf',
            field=models.IntegerField(default=0),
        ),
    ]
