# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_mining', '0006_term_idf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='idf',
            field=models.FloatField(default=0),
        ),
    ]
