# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_mining', '0007_auto_20161126_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='tf_idf_of_all',
            field=models.FloatField(default=0),
        ),
    ]
