# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='facebook_id',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
    ]
