# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 17:42
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0004_comment_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='term_frequency',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
    ]
