# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text_mining', '0001_initial'),
        ('data_parser', '0005_post_term_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermOfPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_parser.Post')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_mining.Term')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='terms',
            field=models.ManyToManyField(through='data_parser.TermOfPost', to='text_mining.Term'),
        ),
    ]
