# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0006_auto_20161017_0606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termofpost',
            old_name='times',
            new_name='quantity',
        ),
    ]
