# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0007_auto_20161017_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mining_check',
            field=models.BooleanField(default=False),
        ),
    ]
