# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0008_post_mining_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termofpost',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data_parser.Post'),
        ),
        migrations.AlterField(
            model_name='termofpost',
            name='term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='text_mining.Term'),
        ),
    ]
