# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0009_auto_20161117_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='termofpost',
            name='tf_idf',
            field=models.IntegerField(default=0),
        ),
    ]
