# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0010_termofpost_tf_idf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termofpost',
            name='tf_idf',
            field=models.FloatField(default=0),
        ),
    ]
