# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-15 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_parser', '0011_auto_20161126_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='school',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
